---
version: "3.8"
services:
  atomdocker:
    image: gregnemeth/atomdocker:0.3.4
    container_name: goatomv2
    environment:
      DISPLAY:
      XDG_CONFIG_HOME:
    volumes:
      - type: volume
        source: gobins
        target: /usr/local/go
      - type: volume
        source: go
        target: /go
      - type: volume
        source: home
        target: /home
      - type: bind
        source: /etc/group
        target: /etc/group:ro
      - type: bind
        source: /etc/passwd
        target: /etc/passwd:ro
      - type: bind
        source: /etc/shadow
        target: /etc/shadow:ro
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix:rw
      - type: bind
        source: /dev/shm
        target: /dev/shm
    devices:
      - /dev/dri/card0:/dev/dri/card0
    network_mode: host
    depends_on:
      - go_engine

  go_engine:
    image: gregnemeth/mygo
    container_name: go_enginev2
    volumes:
      - type: volume
        source: gobins
        target: /usr/local/go
      - type: volume
        source: go
        target: /go

volumes:
  go:
  gobins:
  home:    

